### ISSUE TITLE
Mehr Informationen im mod_banner_empty Template bereitstellen

### ISSUE THREAD

**Issue by cboelter** [BugBuster1701/banner#176]
Hallo,

ich habe bei einem Projekt folgenden Wunsch vom Kunden:

Wenn kein Banner aktiv ist und auch kein Standardbanner, soll ein Frontend-Modul ausgegeben werden. 

Ich habe mir dann überlegt einfach im mod_banner_empty Template das Frontend-Modul via \Controller::getFrontendModule() einzubinden. Problem daran ist, dass es dann natürlich immer wenn mod_banner_empty geladen wird angezeigt wird. Ideal wäre es, wenn ich im Template mod_banner_empty auf alle Informationen der Banner-Kategorie (tl_banner) zugreifen könnte.

Zum testen habe ich in der Datei system/modules/banner/classes/BannerHelper.php in der Zeile 438 einfach mal folgendes ergänzt:

```$this->Template->arrCategoryValues = $this->arrCategoryValues;```

Wäre es möglich diese oder eine ähnliche Lösung in das Modul zu integrieren? Ich kann auch gerne einen PR dafür machen.

**Comment by BugBuster1701** [comment]
Wenn Dir die Zeile reicht, dann baue ich noch ein.

**Comment by cboelter** [comment]
Die Zeile würde ausreichen :-) ... vielen Dank!
