### ISSUE TITLE
404 not found on banner clicking

### ISSUE THREAD

**Issue by hamidpeywasti** [BugBuster1701/banner#179]
When setting an URL (internal und external) for a banner, it return:

Not Found

The requested URL /banner_clicks.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by BugBuster1701** [comment]
Which version of Banner Module do you use?
The actual version used not /banner_clicks.php anymore.

**Comment by hamidpeywasti** [comment]
Hi,
Danke, ich finde mein Problem. Das war von alt Templates.
